civicrm_newsletter.settings:
  type: config_object
  mapping:
    cmrf_connector:
      type: string
      label: 'CiviMRF Connector'
    preferences_autoconfirm:
      type: boolean
      label: 'Confirm subscriptions in preferences form'
    redirect_paths:
      type: mapping
      mapping:
        subscription_form:
          type: string
          label: 'Redirect path for the subscription form'
        optin_page:
          type: string
          label: 'Redirect path for the opt-in page'
        preferences_form:
          type: string
          label: 'Redirect path for the preferences form'
        request_link_form:
          type: string
          label: 'Redirect path for the request-link form'
